# Generated by Django 4.2.27 on 2026-01-31 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0002_initial'),
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='review',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tools.tool'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['shop'], name='tools_shop_id_3b07ec_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['category'], name='tools_categor_c67261_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['is_available'], name='tools_is_avai_74ee2a_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['-created_at'], name='tools_created_5f2ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['shop'], name='reviews_shop_id_2a946a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['tool'], name='reviews_tool_id_1b0133_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='reviews_created_6c5dce_idx'),
        ),
    ]
