# Generated by Django 4.2.27 on 2026-02-27 12:10

from django.db import migrations

def seed_categories(apps, schema_editor):
    ToolCategory = apps.get_model('tools', 'ToolCategory')
    categories = [
        {'name': 'Power Tools', 'slug': 'power-tools', 'icon': 'Zap'},
        {'name': 'Hand Tools', 'slug': 'hand-tools', 'icon': 'Hammer'},
        {'name': 'Lawn & Garden', 'slug': 'lawn-garden', 'icon': 'Leaf'},
        {'name': 'Heavy Machinery', 'slug': 'heavy-machinery', 'icon': 'Truck'},
        {'name': 'Plumbing', 'slug': 'plumbing', 'icon': 'Wrench'},
        {'name': 'Electrical', 'slug': 'electrical', 'icon': 'Lightning'},
        {'name': 'Painting', 'slug': 'painting', 'icon': 'Brush'}
    ]
    for cat in categories:
        ToolCategory.objects.get_or_create(slug=cat['slug'], defaults=cat)

def reverse_seed(apps, schema_editor):
    # Optional: we can just pass here
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_seed),
    ]
